spring.thymeleaf.cache=false
spring.config.import=optional:file:./application-local.properties
server.port=8081
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/idlewheels}
spring.datasource.username=${DB_USERNAME:idlewheels_app}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=validate
idlewheels.storage.local-dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

spring.mvc.format.date=iso
